# Generated by Django 4.0.3 on 2022-03-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('SectionId', models.AutoField(primary_key=True, serialize=False)),
                ('SectionYear', models.IntegerField()),
                ('SectionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.roles')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.sections')),
            ],
        ),
    ]
